# Escutar em todas as interfaces de rede do container
bind 0.0.0.0

# Porta padrão
port 6379

# Desativar modo protegido para permitir conexões de outros containers
protected-mode no

# Desativar o modo daemon (o Redis precisa rodar no primeiro plano para o Docker)
daemonize no

# Configurações recomendadas de memória para cache do WordPress (opcional, mas profissional)
maxmemory 256mb
maxmemory-policy allkeys-lru